version: '3'

services:
  # telnet localhost 22222
  # input_phone_verify_code -code=123456
  futu:
    image: twhtanghk/futu:test
    ulimits:
      nofile:
        soft: 2018
        hard: 2018
    volumes:
      - ./FutuOpenD.xml:/opt/Futu_OpenD_8.8.4818_Ubuntu16.04/Futu_OpenD_8.8.4818_Ubuntu16.04/FutuOpenD.xml
      - ./binance-private-key.pem:/tmp/binance/binance-private-key.pem
    env_file:
      - ../.env
      - ./.env
